version: '3'
services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  mysql:
    image: mysql:8
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql
    env_file:
      - docker/mysql/mysql.env

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  composer:
      build:
        context: docker/composer
        dockerfile: Dockerfile
      volumes:
        - ./src:/var/www/html
