version: '3'
services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root